# Generated by Django 2.2 on 2023-01-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=60, verbose_name='titles')),
                ('price', models.DecimalField(decimal_places=2, default='', max_digits=6, verbose_name='myprice')),
            ],
        ),
    ]
